apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: lights.decorations.easte.rs
spec:
  group: decorations.easte.rs
  names:
    kind: Light
    listKind: LightList
    plural: lights
    singular: light
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
