apiVersion: apps/v1
kind: Deployment
metadata:
  name: christmas-decoration-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: christmas-decoration-operator
  template:
    metadata:
      labels:
        name: christmas-decoration-operator
    spec:
      serviceAccountName: christmas-decoration-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: "quay.io/patrickeasters/christmas-decoration-operator:v0.0.1"
          imagePullPolicy: "{{ pull_policy|default('Always') }}"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: "quay.io/patrickeasters/christmas-decoration-operator:v0.0.1"
          imagePullPolicy: "{{ pull_policy|default('Always') }}"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "christmas-decoration-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: HASS_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: christmas-decoration-operator-hass
                  key: baseURL
            - name: HASS_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: christmas-decoration-operator-hass
                  key: accessToken
      volumes:
        - name: runner
          emptyDir: {}
