---

- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    image_name: decorations.easte.rs/christmas-decoration-operator:testing
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'crds/decorations.easte.rs_v1alpha1_light_cr.yaml'])) | from_yaml }}"
  tasks:
  - name: Create the decorations.easte.rs/v1alpha1.Light
    k8s:
      namespace: '{{ namespace }}'
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/decorations.easte.rs_v1alpha1_light_cr.yaml'])) }}"

  - name: Get the newly created Custom Resource
    debug:
      msg: "{{ lookup('k8s', group='decorations.easte.rs', api_version='v1alpha1', kind='Light', namespace=namespace, resource_name=custom_resource.metadata.name) }}"

  - name: Wait 2m for reconciliation to run
    k8s_facts:
      api_version: 'v1alpha1'
      kind: 'Light'
      namespace: '{{ namespace }}'
      name: '{{ custom_resource.metadata.name }}'
    register: reconcile_cr
    until:
    - "'Successful' in (reconcile_cr | json_query('resources[].status.conditions[].reason'))"
    delay: 12
    retries: 10

- import_playbook: '{{ playbook_dir }}/../default/asserts.yml'
